attachments/config/routes.rb
Brightcontent::Engine.routes.draw do
  get 'attachments/:type/:id' => 'attachments#show', as: :attachments
  post 'attachments/:type/:id/reposition' => 'attachments#reposition'
  match 'attachments' => 'attachments#create', as: :new_attachment, via: [:put, :patch]
  delete 'attachments/:id' => 'attachments#destroy', as: :destroy_attachment
end

attachments/app/models/brightcontent/attachable.rb
module Brightcontent
  module Attachable
    extend ActiveSupport::Concern

    included do
      add_brightcontent_column :attachments
      has_many :attachments, as: :attachable, dependent: :destroy, class_name: Brightcontent::Attachment
    end
  end
end

attachments/app/models/brightcontent/attachment.rb
module Brightcontent
  class Attachment < ActiveRecord::Base
    belongs_to :attachable, polymorphic: true, :inverse_of => :attachments
    has_attached_file :asset, :styles => lambda {|attachment| attachment.instance.attachment_styles }
    before_post_process :resize_images
    before_create :set_position

    default_scope { order("position, id") }
    scope :for_attachable, -> type, id { where(attachable_type: type.classify, attachable_id: id) }

    delegate :url, to: :asset

    validates_attachment_content_type :asset, content_type: Brightcontent.attachment_content_types
    validates :attachable, presence: true
    validates :asset, attachment_presence: true

    attr_accessible *(column_names + [:asset]) if defined? ProtectedAttributes

    def self.reposition!(positions)
      positions.map! &:to_i
      transaction do
        all.each do |attachment|
          attachment.update_column :position, positions.index(attachment.id)
        end
      end
    end

    def attachment_styles
      default_attachment_styles.merge(user_defined_styles)
    end

    def image?
      asset_content_type =~ %r{^(image|(x-)?application)/(bmp|gif|jpeg|jpg|pjpeg|png|x-png)$}
    end

    private

    def user_defined_styles
      if attachable && attachable.class.attachment_styles && image?
        attachable.class.attachment_styles
      end || {}
    end

    def default_attachment_styles
      { brightcontent: "100x100#", main: "200x200#" }
    end

    def resize_images
      return false unless image?
    end

    def set_position
      self.position ||= self.class.for_attachable(attachable_type, attachable_id).maximum(:position).to_i + 1
    end
  end
end

attachments/app/controllers/brightcontent/attachments_controller.rb
require_dependency "brightcontent/application_controller"

module Brightcontent
  class AttachmentsController < ApplicationController
    def show
      @attachments = Attachment.for_attachable(params[:type], params[:id])
      render layout: false
    end

    def create
      @attachment = Attachment.new(attachment_params)
      if @attachment.save
        render json: @attachment.to_json, status: :created
      else
        render json: @attachment.errors, status: :unprocessable_entity
      end
    end

    def destroy
      Attachment.destroy params[:id]
      head :no_content
    end

    def reposition
      Attachment.for_attachable(params[:type], params[:id]).reposition! params[:positions]
      head :no_content
    end

    private

    def attachment_params
      params.require(:attachment).permit(:attachable_id, :attachable_type, :asset)
    end
  end
end

attachments/app/views/brightcontent/attachments/_attachment.html.erb
<li class="list-group-item attachment" data-attachment-id="<%= attachment.id %>">
  <div class="media">
    <% if attachment.image? %>
      <%= image_tag attachment.url(:brightcontent), class: "media-object pull-left" %>
    <% end %>
    <div class="media-body">
      <h4 class="attachment-file media-heading"><%= attachment.asset_file_name %></h4>
      <% if attachment.image? %>
        <%= link_to "Insert", attachment.url(:main), class: "insert insert-image btn btn-primary btn-xs" %>
      <% else %>
        <%= link_to "Insert", attachment.url(:original), class: "insert insert-link btn btn-primary btn-xs", data: { name: attachment.asset_file_name } %>
      <% end %>
      <%= link_to "Delete", destroy_attachment_path(attachment.id), class: "delete btn btn-danger btn-xs", method: :delete %>
    </div>
  </div>
</li>

attachments/app/views/brightcontent/attachments/_form_field.html.erb
<% if item.persisted? %>
  <div id="attachments">
    <% item.attachments.each do |attachment| %>
      <%= image_tag attachment.url %>
    <% end %>
  </div>

  <input id="fileupload" type="file" name="asset" data-url="<%= new_attachment_path %>" multiple>
  <%= hidden_field_tag "attachable_id", item.id %>
  <%= hidden_field_tag "attachable_type", item.class.to_s %>
  <%= hidden_field_tag "attachable_url", attachments_path(item.class.to_s, item.id) %>

<% else %>
  First save to enable uploads
<% end %>

attachments/app/views/brightcontent/attachments/show.html.erb
<%= render @attachments %>

attachments/app/views/brightcontent/base/_form_field_attachments.html.erb
<div class="form-group">
  <label class="control-label col-sm-2"><%=Brightcontent::Attachment.model_name.human.pluralize%></label>
  <div class="col-sm-10" id="attachments-controls">
    <% if item.persisted? %>
      <ul class="media-list" id="attachments">
        <%= render item.attachments %>
      </ul>
      <input id="fileupload" type="file" name="attachment[asset]" data-url="<%= new_attachment_path %>" class="form-control" multiple>
      <%= hidden_field_tag "attachment[attachable_id]", item.id %>
      <%= hidden_field_tag "attachment[attachable_type]", item.class.to_s %>
      <%= hidden_field_tag "attachable_url", attachments_path(item.class.to_s, item.id) %>
    <% else %>
      <p class="form-control-static"><%= t('brightcontent.save_first')%></p>
    <% end %>
  </div>
</div>

attachments/app/views/brightcontent/base/_list_field_attachments.html.erb
<% if item.attachments.any? %>
  <span class="glyphicon glyphicon-paperclip"></span>
  <%= item.attachments.count %>
<% end %>