core/config/routes.rb
Brightcontent::Engine.routes.draw do
  get 'login', to: 'sessions#new'
  get 'logout', to: 'sessions#destroy'

  resources :admin_users
  resources :sessions, only: [:new, :create, :destroy]

  root to: "application#index"
end

core/app/models/brightcontent/admin_user.rb
module Brightcontent
  class AdminUser < ActiveRecord::Base
    has_secure_password
    validates_uniqueness_of :email
    attr_accessible *column_names if defined? ProtectedAttributes

    def self.authenticate(email, password)
      find_by_email(email).try :authenticate, password
    end

    def resources
      Brightcontent::RoutesParser.new.resources
    end
  end
end

core/app/controllers/brightcontent/admin_users_controller.rb
require_dependency "brightcontent/application_controller"

module Brightcontent
  class AdminUsersController < BaseController
    form_fields :email, :password, :password_confirmation

    def resource_class
      Brightcontent.user_model
    end
  end
end

core/app/controllers/brightcontent/application_controller.rb
module Brightcontent
  class ApplicationController < ActionController::Base
    add_flash_types :success, :info, :warning, :danger
    before_action :authorize
    before_action :set_locale
    helper TranslationHelper
    protect_from_forgery

    def index
      redirect_to polymorphic_url(user_resources.first.klass)
    end

    def default_url_options(options = {})
      { locale: I18n.locale }.merge options
    end

    private

    def set_locale
      I18n.locale = params[:locale] || Brightcontent.locale
    end

    def current_user
      @current_user ||= begin
        Brightcontent.user_model.find(session[:brightcontent_user_id]) if session[:brightcontent_user_id]
      end.tap { |u| logger.info "Current Brightcontent user: #{u&.to_gid}" }
    end
    helper_method :current_user

    def user_resources
      @user_resources ||= @current_user.resources
    end
    helper_method :user_resources

    def authorize
      unless current_user
        session[:return_to] = request.original_url
        redirect_to login_url
      end
    end
  end
end

core/app/controllers/brightcontent/base_controller.rb
require 'csv'
require_dependency "brightcontent/application_controller"

module Brightcontent
  class BaseController < ApplicationController
    include BaseControllerExt::DefaultActions
    include BaseControllerExt::Filtering
    include BaseControllerExt::Pagination
    include BaseControllerExt::Fields
  end
end

core/app/controllers/brightcontent/sessions_controller.rb
require_dependency "brightcontent/application_controller"

module Brightcontent
  class SessionsController < ApplicationController
    skip_before_action :authorize

    def new
      redirect_after_login if current_user
    end

    def create
      user = Brightcontent.user_model.authenticate(params[:email], params[:password])
      if user
        session[:brightcontent_user_id] = user.id
        redirect_after_login
      else
        flash.now[:danger] = "Email or password is invalid"
        render :new
      end
    end

    def destroy
      session[:brightcontent_user_id] = nil
      session[:return_to] = nil
      redirect_to root_url
    end

    private

    def redirect_after_login
      redirect_to session.delete(:return_to).presence || root_url
    end
  end
end

core/app/helpers/brightcontent/application_helper.rb
module Brightcontent
  module ApplicationHelper
    def avatar_url(user)
      gravatar_id = Digest::MD5.hexdigest(user.email.downcase)
      "https://gravatar.com/avatar/#{gravatar_id}.png?s=30&d=mm"
    end
  end
end

core/app/helpers/brightcontent/base_helper.rb
module Brightcontent
  module BaseHelper
    def render_list_field(item, field)
      ViewLookup::ListField.new(self, item: item, field: field).call
    end

    def render_filter_field(form, field, options)
      ViewLookup::FilterField.new(self, field: field, form: form, options: options).call
    end

    def render_form_field(form, field)
      ViewLookup::FormField.new(self, item: form.object, field: field, form: form).call
    end

    def render_if_exists(*args)
      render(*args)
    rescue ActionView::MissingTemplate
      nil
    end

    # Returns filter field definitions as a nested array.
    #
    #  [:foo, { bar: { as: :select }, qux: { as: :string } }]
    #
    # Becomes:
    #
    #  [[:foo], [:bar, { as: :select }], [:qux, { as: :string }]]
    #
    def normalized_filter_fields
      filter_fields.flat_map do |field|
        field.is_a?(Hash) ? field.to_a : [[field]]
      end
    end
  end
end

core/app/helpers/brightcontent/translation_helper.rb
module Brightcontent
  module TranslationHelper

    # http://en.wiktionary.org/wiki/nominative_case
    #
    # This implementation works fine for Germanic languages and it will fail
    # horribly at Slavic languages or Arabic. Support for true declensions
    # could be added later though.
    #
    # This method exists because:
    # - we don't want to abuse #human(count: 2) because that should return
    #   something like "2 Users" and not just "Users". It's not meant to say
    #   things like: "These are users"
    # - we want to avoid feeding the current locale to #pluralize the whole time
    #
    # nominative_plural("thing") => "things"
    # nominative_plural(User) => "users"
    # or if I18n.locale == :nl
    #   nominative_plural(User) => "gebruikers"
    #   nominative_plural("thing") => "dingen"
    def nominative_plural(thing)
      if thing.respond_to? :model_name
        nominative_plural(thing.model_name.human)
      else
        I18n.t "#{thing}.title", default: thing.to_s.pluralize(I18n.locale)
      end
    end

    def nominative_singular(thing)
      if thing.respond_to? :model_name
        nominative_singular(thing.model_name.human)
      else
        I18n.t "#{thing}.title", default: thing.to_s.singularize(I18n.locale)
      end
    end

  end
end

core/app/helpers/brightcontent/translation_heper.rb
module Brightcontent
  module TranslationHelper

    # http://en.wiktionary.org/wiki/nominative_case
    #
    # This implementation works fine for Germanic languages and it will fail
    # horribly at Slavic languages or Arabic. Support for true declensions
    # could be added later though.
    #
    # This method exists because:
    # - we don't want to abuse #human(count: 2) because that should return
    #   something like "2 Users" and not just "Users". It's not meant to say
    #   things like: "These are users"
    # - we want to avoid feeding the current locale to #pluralize the whole time
    #
    # nominative_plural("thing") => "things"
    # nominative_plural(User) => "users"
    # or if I18n.locale == :nl
    #   nominative_plural(User) => "gebruikers"
    #   nominative_plural("thing") => "dingen"
    def nominative_plural(thing)
      case thing
      when ActiveRecord::Base
        nomative_plural(thing.model_name.human)
      when String
        I18n.t "#{string}.title", default: string.pluralize(I18n.locale)
      end
    end

    def nominative_singular(thing)
      case thing
      when ActiveRecord::Base
        nomative_plural(thing.model_name.human)
      when String
        I18n.t "#{string}.title", default: string.singularize(I18n.locale)
      end
    end

  end
end

core/app/views/brightcontent/application/_menu.html.erb
<%= render user_resources.main_menu %>

<% if user_resources.extra_menu? %>
  <li class="dropdown">
    <a href="#" class="dropdown-toggle" data-toggle="dropdown"><%= t('brightcontent.extra_menu') %> <b class="caret"></b></a>
    <ul class="dropdown-menu">
      <%= render user_resources.extra_menu %>
    </ul>
  </li>
<% end %>

core/app/views/brightcontent/application/_resource.html.erb
<li class="<%= 'active' if resource_class == resource.klass %>">
  <%= link_to nominative_plural(resource.klass).capitalize, polymorphic_url(resource.klass) %>
</li>

core/app/views/brightcontent/application/_show_flash_names.html.erb
<% flash.each do |key,value| %>
  <div class="alert alert-info">
    <a class="close" data-dismiss="alert" href="#" aria-hidden="true">&times;</a>
    <%= value %>
  </div>
<% end %>

core/app/views/brightcontent/application/_user_menu.html.erb
<li><%= link_to "Homepage", "/" %></li>
<li><%= link_to nominative_plural(Brightcontent.user_model), admin_users_path %></li>
<li class="divider"></li>
<li><%= link_to t('brightcontent.logout'), logout_path %></li>

core/app/views/brightcontent/base/_form.html.erb
<%= simple_form_for resource_path do |form| %>
  <%= form.error_notification %>

  <div class="page-header">
    <h1><%= t('brightcontent.' + (resource.new_record? ? 'create_new' : 'edit_model'), model: resource_class.model_name.human).capitalize %></h1>
  </div>

  <div class="panel-body form-fields">
    <% form_fields.each do |form_field| %>
      <%= render_form_field(form, form_field) %>
    <% end %>
  </div>

  <div class="panel-footer">
    <%= form.button :submit, class: "btn btn-primary" %>
    <%= form.button :submit, t('brightcontent.save_and_continue'), class: "btn btn-default", name: "commit_and_continue" %>

    <% unless resource.new_record? %>
      <%= link_to t('brightcontent.delete'), resource_path, class: "btn btn-danger pull-right", method: :delete, data: { confirm: 'Are you sure?' } %>
    <% end %>
  </div>
<% end %>

core/app/views/brightcontent/base/_list_actions.html.erb
<%= link_to t('brightcontent.edit'), resource_edit_path(item), class: "btn btn-xs btn-primary" %>
<%= link_to t('brightcontent.delete'), resource_path(item), class: "btn btn-xs btn-danger", data: {confirm: t('brightcontent.are_you_sure')}, method: :delete %>

core/app/views/brightcontent/base/_list_filters.html.erb
<% if filter_fields.present? %>
  <div class="panel-body">
    <%= search_form_for ransack_search, class: "form-inline" do |form| %>
      <%= hidden_field_tag :per_page, items_per_page %>
      <% normalized_filter_fields.each do |field, options| %>
        <%= render_filter_field form, field, options %>
      <% end %>
      <%= form.submit class: "btn btn-default btn-sm" %>
    <% end %>
  </div>
<% end %>

core/app/views/brightcontent/base/_list_header.html.erb
<div class="page-header">
  <%= link_to "#{I18n.t('brightcontent.create_new', model: resource_class.model_name.human).capitalize}", url_for(action: :new), class: "btn btn-primary pull-right" %>
  <h1><%= nominative_plural(resource_class).capitalize %></h1>
</div>

<%= render_if_exists "index_top" %>

core/app/views/brightcontent/base/_list_item.html.erb
<%= content_tag :tr, id: dom_id(item), class: dom_class(item) do %>
  <% list_fields.each do |field| %>
    <td><%= render_list_field(item, field) %></td>
  <% end %>
  <td class="list-actions"><%= render "list_actions", item: item %></td>
<% end %>

core/app/views/brightcontent/base/_page_sizes.html.erb
<% if page_sizes_visible?(collection) %>
  <ul class="pagination page-sizes pull-left">
    <% page_sizes.each do |size| %>
      <li class="<%= :active if size == items_per_page %>">
        <%= link_to size, params.permit!.merge({ per_page: size, page: corrected_page(size) }) %>
      </li>
    <% end %>
  </ul>
<% end %>

core/app/views/brightcontent/base/edit.html.erb
<%= render "form" %>

core/app/views/brightcontent/base/form_fields/_belongs_to.html.erb
<%= form.association field.to_sym %>

core/app/views/brightcontent/base/form_fields/_date.html.erb
<div class="form-group">
  <%= form.label field %>
  <div class="col-sm-10">
    <%= form.text_field field, class: 'form-control', data: {behaviour: 'datepicker', format: "dd/MM/yyyy"} %>
    <span class="add-on">
      <i data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
</div>

core/app/views/brightcontent/base/form_fields/_datetime.html.erb
<div class="form-group">
  <%= form.label field %>
  <div class="col-sm-10">
    <%= form.text_field field, class: 'form-control', data: {behaviour: 'datetimepicker', format: "dd/MM/yyyy HH:mm"} %>
    <span class="add-on">
      <i data-time-icon="icon-clock" data-date-icon="icon-calendar">
      </i>
    </span>
  </div>
</div>

core/app/views/brightcontent/base/form_fields/_file.html.erb
<%= form.input field %>
<% if item.send(field).present? && item.send(field).content_type =~ /^image\// %>
  <div class="form-group file-preview">
    <div class="col-sm-offset-2 col-sm-10">
      <%= image_tag item.send(field).url(item.send(field).styles.keys.first) %>
    </div>
  </div>
<% end %>

core/app/views/brightcontent/base/form_fields/_has_and_belongs_to_many.html.erb
<%= form.association field.to_sym, as: :check_boxes %>

core/app/views/brightcontent/base/form_fields/_has_many.html.erb
<%= form.association field.to_sym, as: :check_boxes %>

core/app/views/brightcontent/base/index.csv.erb
<%== CSV.generate(:col_sep => ";", :quote_char => '"') do |csv| %>
  <% csv << default_fields %>
  <% collection.each do |item| %>
    <% csv << default_fields.map { |field| item.send(field) } %>
  <% end %>
<% end %>

core/app/views/brightcontent/base/index.html.erb
<%= render "list_header" %>

<%= render "list_filters" %>

<div class="table-responsive">
  <table class="table table-hover <%= dom_class(resource_class, :table) %>">
    <thead>
      <tr>
        <% list_fields.each do |list_field| %>
          <th><%= resource_class.human_attribute_name(list_field) %></th>
        <% end %>
        <th></th>
      </tr>
    </thead>
    <tbody>
      <%= render partial: 'list_item', collection: collection, as: :item %>
    </tbody>
  </table>
</div>

<div class="panel-footer panel-footer-pagination">
  <%= render partial: "page_sizes" %>
  <%= will_paginate collection, class: :pages, renderer: Brightcontent::PaginationRenderer %>
</div>

core/app/views/brightcontent/base/list_fields/_boolean.html.erb
<% if item.send(field) %>
  <span class="glyphicon glyphicon-ok"></span>
<% else %>
  <span class="list-false">&times;</span>
<% end %>

core/app/views/brightcontent/base/list_fields/_has_and_belongs_to_many.html.erb
<%= item.send(field).count %>

core/app/views/brightcontent/base/list_fields/_has_many.html.erb
<%= item.send(field).count %>

core/app/views/brightcontent/base/new.html.erb
<%= render "form" %>

core/app/views/layouts/brightcontent/_content.html.erb
<div class="<%= "panel panel-default" unless controller.controller_name == 'sessions' %>">
  <%= render "brightcontent/application/show_flash_names" %>
  <%= yield %>
</div>

core/app/views/layouts/brightcontent/_navbar.html.erb
<% if current_user %>
  <div class="navbar navbar-inverse navbar-bc navbar-static-top" role="navigation">
    <div class="container">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to Brightcontent.application_name, root_path, class: "navbar-brand" %>
      </div>
      <div class="navbar-collapse collapse">
        <ul class="nav navbar-nav js-menu">
          <%= render "menu" %>
        </ul>
        <ul class="nav navbar-nav navbar-right">
          <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown">
            <%= image_tag avatar_url(current_user), class: 'avatar' %>
            <%= current_user.email %><b class="caret"></b>
          </a>
          <ul class="dropdown-menu">
            <%= render "brightcontent/application/user_menu" %>
          </ul>
          </li>
        </ul>
      </div>
    </div>
  </div>
<% end %>

core/app/views/layouts/brightcontent/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Brightcontent.application_name %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex" />
  <%= stylesheet_link_tag "brightcontent/brightcontent", :media => "all" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>

<body data-editor-locale="<%=t('brightcontent.editor_locale')%>">
  <% if current_user %>
    <div class="navbar navbar-inverse navbar-bc navbar-static-top" role="navigation">
      <div class="container">
        <div class="navbar-header">
          <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
            <span class="sr-only">Toggle navigation</span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
            <span class="icon-bar"></span>
          </button>
          <%= link_to Brightcontent.application_name, root_path, class: "navbar-brand" %>
        </div>
        <div class="navbar-collapse collapse">
          <ul class="nav navbar-nav js-menu">
            <%= render "menu" %>
          </ul>
          <ul class="nav navbar-nav navbar-right">
            <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
              <%= image_tag avatar_url(current_user), class: 'avatar' %>
              <%= current_user.email %><b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
              <%= render "brightcontent/application/user_menu" %>
            </ul>
            </li>
          </ul>
        </div>
      </div>
    </div>
  <% end %>

  <div class="container">
    <div class="<%= "panel panel-default" unless controller.controller_name == 'sessions' %>">
      <%= render "brightcontent/application/show_flash_names" %>
      <%= yield %>
    </div>
  </div>
</div>

<%= javascript_include_tag "brightcontent/brightcontent" %>
<%= yield :bottom %>
</body>
</html>

core/app/views/layouts/brightcontent/wide.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= Brightcontent.application_name %></title>
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="robots" content="noindex" />
  <%= stylesheet_link_tag "brightcontent/brightcontent", :media => "all" %>
  <%= yield :head %>
  <%= csrf_meta_tags %>
</head>

<body data-editor-locale="<%=t('brightcontent.editor_locale')%>">
  <%= render 'layouts/brightcontent/navbar' %>

  <div class="container-wide">
    <%= render 'layouts/brightcontent/content' %>
  </div>
</div>

<%= javascript_include_tag "brightcontent/brightcontent" %>
<%= yield :bottom %>
</body>
</html>